### PR TITLE
Extend workshop announcement

### PR DESCRIPTION
**Pull request by hgascon**

### CODE REVIEW

**Comment by hgascon** [comment]
Feel free to review and add fixes to the text.

**Review by mhils — COMMENTED** [review]
I really appreciate you putting effort into this, but some parts currently read a bit like an overly enthusiastic ChatGPT if I'm being honest. For me personally that'd be a bit of a red flag. Can we tune down the language a bit maybe?

**Comment by hgascon** [comment]
Absolutely. I actually tried to tune it down already but I guess I still haven't found the right tone. Feel free to make suggestions or change everything. In any case I think we need something that we can start sharing on social media asap.

**Review by glaslos — APPROVED** [review]
LGTM

**Pull request merged**
