### PR TITLE
new blog post for gsoc 2023 intelowl

### PR DESCRIPTION
**Pull request by mlodic**

### CODE REVIEW

**Comment by xandfury** [comment]
Thanks for this @mlodic. The post at IntelOwl website looks great. 

I just feel that since the intern worked with THP, the post on THP website should have more details instead of the link.

**Comment by mlodic** [comment]
Honestly I prefer to redirect instead of copy/pasting the same article.

**Comment by mhils** [comment]
I think you both have a point here. Linking to a more detailed blog post on the project's website is very reasonable IMO. I'd like to do the same for mitmproxy as well. That being said, having a brief summary on what was done over the summer right on the Honeynet blog is a) a better teaser for the in-depth version and b) makes the Honeynet blog more interesting to read. :)

@mlodic @xandfury: Please take a look at https://github.com/honeynet/honeynet.github.io/compare/gsoc_2023_io...intelowl-max-reword and let me know what you think. My focus was to 1) explain terms that may be unfamiliar to the reader (GSoC, IntelOwl, BuffaLogs), and 2) add a super short summary. @mlodic feel free to reword/change things of course. :)

**Comment by hgascon** [comment]
My suggestion:

---
Our dedicated Google Summer of Code (GSoC) participant, [Abheek](https://twitter.com/abheekblahblah), has spent an impressive three-month duration program actively contributing to not one, but two distinct projects: [IntelOwl](https://intelowlproject.github.io/) and [Buffalogs](https://github.com/certego/BuffaLogs). Notably, Abheek undertook the responsibility of crafting the brand-new official website for IntelOwl throughout this period.

In light of this significant achievement, we believe it is only fitting to showcase his remarkable results and contributions within the official IntelOwl site, in which he discuses
his journey as a designer/frontend developer, the tasks involved and the detailed contributions to both projects, including the revamping of IntelOwl's website, implementing JWT authentication for Buffalogs, creating maps and graphs for BuffaLogs' dashboard, and crafting a frontend guide for IntelOwl using react-joyride.

We invite you to explore the comprehensive summary of Abheek's GSoC 2023 journey in our [official project blog post](https://intelowlproject.github.io/blogs/gsoc23_project_summary), and hope you find it a valuable resource to gain deeper insights into Abheek's accomplishments during the program and how it has helped strengthen his commitment to open-source.
---

**Comment by mlodic** [comment]
for me both suggestions are great, feel free to merge the one that you feel more appropriate.

**Comment by mhils** [comment]
Either is good, @hgascon please go ahead and merge your stuff! 😃

**Review by hgascon — APPROVED** [review]

**Pull request merged**
